name: CI Pipeline

on:
  push:
    branches:
      - main
      - test-ci-fix

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Java setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Maven build
        run: ./mvnw -f backend/pom.xml clean verify
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
          #TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal" #-----  UNCOMMENT ONLY FOR LOCAL TESTING USING DOCKER DESKTOP ON WINDOWS OS ----- 
          TESTCONTAINERS_RYUK_DISABLED: "true"
  
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
        working-directory: ./backend

      - name: Enforce test coverage threshold
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: backend/target/site/jacoco/jacoco.csv
          jacoco-xml-file: backend/target/site/jacoco/jacoco.xml
          coverage-threshold: 80
          fail-if-below-threshold: true

      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t myapp:latest .